apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Release.Time.Seconds }}
  namespace: {{ .Values.namespace }}
  {{ if .Values.service.annotations }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{ end }}
  labels:
    app: {{ tpl .Values.labels.app . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app: {{ tpl .Values.labels.app . }}
