---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ tpl .Values.persistence.claimName . }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: pure-file
